### ISSUE TITLE
ERROR:root:Property type Edm.Byte is not supported by mutator yet

### ISSUE THREAD

**Issue by AlapanGhosh** [SAP/odfuzz#62] opened 2020-06-16 09:39 UTC
How to resolve this?

**Comment by jfilak** [comment] 2020-06-16 10:33
We have to add support OData V4 to SAP/python-pyodata.

**Comment by jfilak** [comment] 2020-06-17 10:48
Please, ignore my comment. I have no idea why I thought we need OData V4.

**Comment by phanak-sap** [comment] 2020-07-04 21:36
I am marking this as duplicate of  #61

**Closed by phanak-sap** 2020-07-04 21:36 UTC
