### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by si90** [SAP/odfuzz#42] opened 2020-04-21 19:04 UTC
When running on my host (without docker) against a large OData service, I get the following error message:

`config.err_policy(ParserError.ENTITY_TYPE).resolve(ex)
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 59, in resolve
    raise ekseption
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 989, in from_etree
    etype = EntityType.from_etree(entity_type, config)
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 1388, in from_etree
    navp = NavigationTypeProperty.from_etree(proprty)
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 1705, in from_etree
    node.get('Name'), node.get('FromRole'), node.get('ToRole'), Identifier.parse(node.get('Relationship')))
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 156, in parse
    parts = value.split('.')
AttributeError: 'NoneType' object has no attribute 'split'
  `

**Comment by phanak-sap** [comment] 2020-04-24 05:40
Hi, thx for using odfuzz.  Providing just the part of errors without any additional information is not really actionable.

- provide longer stacktrace, this seems to be cut at the very end, see log.txt in generated results directory. This is deep in library calls and it may be usefull to see the odfuzz stacktraces as well.
- if it is public Odata service that I can test against, please add its URL. 
- if not, please provide version of the odata protocol (v2, v3, v4) and please provide the service metadata model (for example as Gist); since this error originated from the pyodata lib in runtime, it may be well possible that the metadata are invalid in structure.
- even tho it does not seems at the moment relevant, provide the URL which was generated before the crash; you can replace the domain name if it is private service and just leave the generated URL part, starting with the entity set.

At the moment I cannot reproduce this or even wildly guess.

**Comment by phanak-sap** [comment] 2020-07-04 21:53
Since no comment from April and the issue is not actionable, closing. Repoen with more data as requested by my comment.

**Closed by phanak-sap** 2020-07-04 21:53 UTC
Labels: investigation
